### ISSUE TITLE
Uncaught TypeError: sortable is not a function

### ISSUE THREAD

**Issue by CWSites** [lukasoppermann/html5sortable#423]
### I'm opening this issue because:
I get the following error `Uncaught TypeError: sortable is not a function` no matter how I attempt to import your library into my application. It worked perfectly with version 0.5.1 but upgrading to 0.9.2 breaks it.

### supporting information:
- I use sortable version: 0.9.2
- I tested in the following browser (incl. versions): Chrome 65.0.3325.181
- Windows, OS X/macOS, or Linux?: macOS

### How can the issue be reproduce the problem?
I am installing your package with npm, when I upgraded from 0.5.1 > 0.9.2 I am no longer able to import. I tried to import the following ways and none of them worked.

1. `import 'html5sortable';`
2. `import sortable from 'html5sortable';`
3. `import 'node_modules/html5sortable/dist/html5sortable.js';`
4. `const sortable = require('node_modules/html5sortable/dist/html5sortable.js');`

**Comment by lukasoppermann** [comment]
Hey @CWSites,

you need to make sure you are requiring the correct file: https://github.com/lukasoppermann/html5sortable/tree/master/dist

For es6 modules you need to require `dist/html5sortable.es.js` for cjs `dist/html5sortable.cjs.js`.

Hope that helps.

**Comment by CWSites** [comment]
Hey @lukasoppermann thanks for the quick response, I tried importing both of those as well but I had the same issue.

EDIT: I'm not sure if it matters but I'm doing this in a React app using babel and webpack. I've pulled in your package via npm and I'm importing the file at the top of the component that needs it.

**Comment by lukasoppermann** [comment]
Hey, so it is working fine for me, I just tested with the `import sortable from 'node_modules/html5sortable/dist/html5sortable.es.js'` are you sure that you are not running into any race conditions?

Can you somehow show more of your code? 
I guess this is not the only es6 package you are importing, correct? So others work fine?

**Comment by CWSites** [comment]
That worked, thank you @lukasoppermann, the one method I didn't try was the way you just posted.

**Comment by lukasoppermann** [comment]
Nice, happy it helped. 👍

**Comment by gilbertoalbino** [comment]
> Hey @CWSites,
> 
> you need to make sure you are requiring the correct file: https://github.com/lukasoppermann/html5sortable/tree/master/dist
> 
> For es6 modules you need to require `dist/html5sortable.es.js` for cjs `dist/html5sortable.cjs.js`.
> 
> Hope that helps.

it seems like it is the most foundational information that IS NOT in the instalation guide. 
Javascript opensource sucks sometimes!

**Comment by lukasoppermann** [comment]
Wait, am I missing something? @gilbertoalbino so it says which version to use under the installation section in the docs. What is missing?

**Comment by gilbertoalbino** [comment]
Sorry, my bad english.
I was trying to say that the link is broken, so that I could not find what you are recommending:
https://github.com/lukasoppermann/html5sortable/tree/master/dist (404 page not found)

**Comment by lukasoppermann** [comment]
Good catch, should be fixed now.

**Comment by gilbertoalbino** [comment]
yep! it's fixed now! Thanks :D
